print("Reversed name creator")
first_name = (input("What is your first name?"))
print(first_name)
first_reversed = " ".join(word[::-1] for word in first_name.split()).title()
last_name = (input("What is your last name?"))
last_reversed = last_name[::-1].title()
print(last_name)
print(first_reversed +" "+ last_reversed)